
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Employee extends javax.swing.JFrame {
    
Connection conn;
     private Statement stat;
    public Employee() {
        initComponents();
        createconnection();
    }
void createconnection()  {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/supershop", "root", "");
           
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jaddemp = new javax.swing.JButton();
        jremove = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jdisplay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jsearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee Inormation");

        jLabel3.setText("Phone Number");

        jaddemp.setText("Add Employee");
        jaddemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddempActionPerformed(evt);
            }
        });

        jremove.setText("Remove Employee");
        jremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremoveActionPerformed(evt);
            }
        });

        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jdisplay.setText("Display");
        jdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdisplayActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Phone No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jsearch.setText("Search");
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jphone, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(62, 62, 62))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jname)
                                    .addComponent(jid, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jremove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jaddemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jaddemp)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jremove)
                        .addGap(18, 18, 18)
                        .addComponent(jupdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdisplay)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaddempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddempActionPerformed
 try {
     int phone,id;
     
 String ename = jname.getText();
 phone = Integer.parseInt(jphone.getText());
 id = Integer.parseInt(jid.getText());
         //insert query
         PreparedStatement stat;
         String query ="INSERT INTO employee (name,phone,id)" +"  values (? , ?, ?  )";
            stat = conn.prepareStatement(query);
             stat.setString(1, ename);
              stat.setInt(2, phone);
               stat.setInt(3, id);
                
                 if (jname.getText().isEmpty()){
                     
                     System.out.println("Plz Fill up blanks");
                  
                 }
                 else if (jphone.getText().isEmpty()){
                   System.out.println("Plz Fill up blanks");
                 }
                 
                 
                 else if (jid.getText().isEmpty()){
                   System.out.println("Plz Fill up blanks");
                 }
                     
                 else {
                     stat.execute();
                  jname.setText(" ");
                 
                  jphone.setText(" ");
                  jid.setText(" ");
                  conn.close();
                 }
            
     } catch (SQLException ex) {
         Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
     }


            


        // TODO add your handling code here:
    }//GEN-LAST:event_jaddempActionPerformed

    private void jremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremoveActionPerformed
        
        try{
           //Connection conn;
        Class.forName("com.mysql.jdbc.Driver");
        
         conn = DriverManager.getConnection("jdbc:mysql://localhost/supershop", "root", "");
         String sql="delete from employee  where id=?";
         PreparedStatement stat=conn.prepareStatement(sql);
         
         stat.setInt(1,Integer.parseInt(jid.getText()) );
         stat.executeUpdate();
         JOptionPane.showMessageDialog (null," Deleted Successfully");
         conn.close();
         
          jid.setText("");
          jname.setText("");
          jphone.setText("");
   
    }


catch(Exception e)

{
JOptionPane.showMessageDialog (null,"Something is Wrong.Please check again.");

} 
        
        
        
    }//GEN-LAST:event_jremoveActionPerformed

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
        
         try{
        Class.forName("com.mysql.jdbc.Driver");
        
         conn = DriverManager.getConnection("jdbc:mysql://localhost/supershop", "root", "");
        
        String sql="select * from employee where id=?";
        
        
       PreparedStatement stat=conn.prepareStatement(sql);
       stat.setInt(1,Integer.parseInt(jid.getText()));
       ResultSet rs=stat.executeQuery();
       if(rs.next())
       {
           jid.setText(rs.getString("ID"));
           jname.setText(rs.getString("Name"));
           jphone.setText(rs.getString("Phone"));
       
       
       }
       else{
       
         JOptionPane.showMessageDialog(null, "Not Found");
       }
       
       conn.close();
      }
        
        catch(Exception e){
            
            
            JOptionPane.showMessageDialog(null, e);
           
        }
     
    }//GEN-LAST:event_jsearchActionPerformed

    private void jdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdisplayActionPerformed
       
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
       
        try {
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery("select * from employee");
            while (rs.next()) {
             int  i;  
               
            String n = rs.getString("name");
             i = rs.getInt("id");
            int p = rs.getInt("phone");
            
            tableModel.addRow(new Object[] {n,i,p});
           
            }
           stat.close();
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jdisplayActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed

        try{

            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost/supershop", "root", "");
            // String sql="update product set id=?,name=?,quantity=?,price=? where id=?";
            // PreparedStatement stat=conn.prepareStatement(sql);
            stat=conn.createStatement();
            // st.setInt(1,Integer.parseInt(jproid.getText()));
            // st.setString(2,jproname.getText());
            // st.setInt(3,Integer.parseInt(jquan.getText()));
            //  st.setInt(4,Integer.parseInt(jprice.getText()));
            int ID = Integer.parseInt(jid.getText());
            String Name =jname.getText();
            int Phone = Integer.parseInt(jphone.getText());

            String q1 = "update employee set id='"+ID+"', name='"+Name+"',phone='"+Phone+"'";
            stat.executeUpdate(q1);

            // st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            this.jdisplay.enable();
            // conn.close();

        }

        catch(  Exception ex){

            JOptionPane.showMessageDialog(null,ex);
    }//GEN-LAST:event_jupdateActionPerformed
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jaddemp;
    private javax.swing.JButton jdisplay;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jphone;
    private javax.swing.JButton jremove;
    private javax.swing.JButton jsearch;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables
}
